### PR TITLE
Added deps.edn

### PR DESCRIPTION
**Pull request by simonbronner**
Hi Christian - deps.edn as generated off the project.clj by depify  (https://github.com/hagmonk/depify).

### CODE REVIEW

**Comment by whilo** [comment]
Thanks. For which use cases does this help? I guess it helps the clj tool to resolve dependencies? So far I have only used leiningen to be honest.

**Comment by simonbronner** [comment]
Yeah that's it. It tends to find it gives users a bit more control over what cut of a library they're using (without actually building it locally) since they can refer to a specific commit in their deps.edn - rather than waiting for a new maven artefact. e.g:
`io.replikativ/hitchhiker-tree {:git/url "https://github.com/replikativ/hitchhiker-tree"
                               :sha "ee2e0fec12953bfae7f56c51a78024bb5362d2cc"}
`
(no more "can you cut a release with the the latest fixes please")

https://github.com/RickMoynihan/lein-tools-deps gives you the best of both worlds - managing dependencies via deps.edn, but with the power of a proper build tool. If you're interested I can create a pull request to do this, otherwise I can just track any dependency changes in the repo and keep the deps.edn up to date.

**Comment by whilo** [comment]
A pull-request implementing the combination would be nice :).

**Comment by TimoKramer** [comment]
We have switched to clojure cli tools now on development branch. This PR is obsolete then.

**Pull request closed without merging**
