### PR TITLE
Restore release 0.1.9

### PR DESCRIPTION
**Pull request by TimoKramer**
tests are unfortunately failing. @whilo any idea on why it is failing because of:
```
$ lein test
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Syntax error (IllegalAccessError) compiling at (hitchhiker/konserve_test.cljc:1:1).
list-keys is not public

Full report at:
/tmp/clojure-15479272072895312237.edn
Tests failed.
```

### CODE REVIEW

**Comment by whilo** [comment]
Unless we are ready to use konserve 0.6.0, we should not bump this dependency yet. If we want to start do so, we need to use the `konserve.core/keys` instead of `list-keys` function now, this is what the error is about.

**Comment by TimoKramer** [comment]
For this PR I unpacked the hitchhiker-tree-0.1.9.jar from my local repo and copied it over the main branch. You can have a look at the pom in the 0.1.9 release that is already a few months old and there you can find 
```
    <dependency>
      <groupId>io.replikativ</groupId>
      <artifactId>konserve</artifactId>
      <version>0.6.0-alpha1</version>
    </dependency>
```
In the jar there are no tests so I am not sure what to change in the tests to make it green.

**Comment by TimoKramer** [comment]
@groundedSAGE @whilo feel free to merge.

**Review by whilo — APPROVED** [review]
Thanks a lot @TimoKramer !

**Pull request merged**
